# Comprehensive career database with detailed descriptions for ML processing
CAREER_DATABASE = {
    # Technology & IT Careers
    "Software Engineer": "Develops software applications, writes code, designs systems, works with programming languages, debugging, software architecture, full-stack development, mobile apps, web applications, computer science, engineering",
    "Data Scientist": "Analyzes data, machine learning, statistical modeling, Python programming, data visualization, predictive analytics, big data, artificial intelligence, research, algorithms, mathematics, statistics",
    "AI/ML Engineer": "Machine learning, artificial intelligence, neural networks, deep learning, Python, TensorFlow, PyTorch, model training, algorithm development, automation, robotics, computer vision",
    "Cybersecurity Analyst": "Security, network protection, threat analysis, ethical hacking, information security, risk assessment, firewall, encryption, security protocols, incident response, digital forensics",
    "Web Developer": "Frontend development, backend development, HTML, CSS, JavaScript, React, Node.js, web applications, user interface, responsive design, API development, full-stack",
    "Mobile App Developer": "iOS development, Android development, mobile applications, Swift, Kotlin, React Native, Flutter, app design, user experience, mobile UI/UX, cross-platform",
    "DevOps Engineer": "Cloud computing, automation, CI/CD, Docker, Kubernetes, AWS, Azure, infrastructure, deployment, monitoring, system administration, Linux, server management",
    "Cloud Architect": "Cloud computing, AWS, Azure, Google Cloud, system design, scalability, infrastructure, security, cost optimization, migration, architecture planning, distributed systems",
    "Database Administrator": "Database management, SQL, data modeling, performance tuning, backup, recovery, data security, Oracle, MySQL, PostgreSQL, data warehousing, data integrity",
    "Network Engineer": "Network design, routing, switching, TCP/IP, Cisco, network security, troubleshooting, wireless networks, network monitoring, infrastructure, telecommunications",
    "UI/UX Designer": "User interface design, user experience, prototyping, Figma, Adobe XD, wireframing, usability testing, design thinking, visual design, interaction design, user research",
    "Product Manager": "Product strategy, market research, user requirements, project management, stakeholder management, product roadmap, analytics, business analysis, leadership, agile",
    "Technical Writer": "Documentation, technical communication, writing, user manuals, API documentation, content creation, editing, research, software documentation, technical content",
    "IT Consultant": "Technology consulting, system analysis, business process improvement, project management, client relations, technical expertise, problem solving, strategy, digital transformation",
    "System Administrator": "Server management, system maintenance, user support, network administration, security, backup, monitoring, troubleshooting, Linux, Windows, IT infrastructure",
    "Game Developer": "Game programming, Unity, Unreal Engine, C++, game design, 3D modeling, animation, game physics, mobile games, console games, indie development",
    "Blockchain Developer": "Blockchain technology, cryptocurrency, smart contracts, Solidity, Ethereum, distributed systems, cryptography, DeFi, Web3, digital assets",
    "Robotics Engineer": "Robotics, automation, mechanical engineering, programming, AI, machine learning, sensors, control systems, industrial automation, research and development",
    
    # Healthcare & Medical Careers
    "Doctor": "Medical practice, patient care, diagnosis, treatment, surgery, medical research, healthcare, anatomy, physiology, pharmacology, clinical skills, medicine, hospital",
    "Nurse": "Patient care, medical assistance, healthcare, clinical skills, patient monitoring, medication administration, healthcare coordination, compassion, medical knowledge, hospital",
    "Pharmacist": "Medication management, drug interactions, prescription filling, patient counseling, pharmaceutical knowledge, healthcare, clinical pharmacy, drug safety, medicine",
    "Physical Therapist": "Rehabilitation, physical therapy, patient care, exercise therapy, injury recovery, movement analysis, therapeutic exercises, healthcare, anatomy, sports medicine",
    "Dentist": "Dental care, oral health, dental procedures, patient care, dental surgery, preventive care, dental hygiene, oral medicine, dental technology, orthodontics",
    "Veterinarian": "Animal care, veterinary medicine, animal health, surgery, diagnosis, treatment, pet care, animal welfare, medical knowledge, clinical skills, zoology",
    "Medical Researcher": "Medical research, clinical trials, data analysis, scientific research, healthcare innovation, laboratory work, statistical analysis, medical knowledge, biotechnology",
    "Healthcare Administrator": "Healthcare management, hospital administration, healthcare policy, budget management, staff coordination, healthcare operations, leadership, healthcare systems",
    "Radiologist": "Medical imaging, X-rays, MRI, CT scans, diagnostic imaging, medical diagnosis, radiology, medical technology, patient care, medical knowledge, imaging technology",
    "Surgeon": "Surgical procedures, patient care, medical surgery, operating room, surgical skills, medical knowledge, patient safety, clinical expertise, healthcare, specialized surgery",
    "Psychologist": "Mental health, psychological assessment, therapy, counseling, behavioral analysis, research, clinical psychology, patient care, mental wellness, cognitive therapy",
    "Nutritionist": "Nutrition counseling, dietary planning, health education, food science, wellness, clinical nutrition, public health, dietary analysis, health promotion, food safety",
    "Biomedical Engineer": "Medical devices, engineering, healthcare technology, research, product development, medical equipment, innovation, technical skills, healthcare, medical technology",
    "Medical Technologist": "Laboratory testing, medical technology, diagnostic testing, clinical laboratory, medical equipment, quality control, healthcare, technical skills, pathology",
    "Occupational Therapist": "Rehabilitation, patient care, therapy, healthcare, helping patients, medical assistance, treatment planning, patient recovery, healthcare services",
    "Speech Therapist": "Speech therapy, language therapy, patient care, healthcare, communication disorders, rehabilitation, helping patients, medical assistance, therapy services",
    "Emergency Medical Technician": "Emergency care, medical assistance, healthcare, patient care, ambulance, emergency response, medical knowledge, first aid, healthcare services",
    "Medical Laboratory Scientist": "Laboratory work, medical testing, healthcare, research, diagnostic testing, medical technology, laboratory analysis, healthcare services, medical knowledge",
    
    # Business & Finance Careers
    "Business Analyst": "Business analysis, data analysis, requirements gathering, process improvement, project management, stakeholder management, business intelligence, strategy, consulting",
    "Marketing Manager": "Marketing strategy, digital marketing, brand management, market research, advertising, social media, campaign management, analytics, leadership, brand development",
    "Financial Analyst": "Financial analysis, investment analysis, financial modeling, risk assessment, market research, financial planning, data analysis, economics, investment banking",
    "Investment Banker": "Investment banking, financial services, mergers and acquisitions, capital markets, financial analysis, client relations, deal structuring, finance, corporate finance",
    "Management Consultant": "Business consulting, strategy consulting, process improvement, change management, business analysis, client relations, problem solving, leadership, organizational development",
    "Entrepreneur": "Business development, innovation, leadership, risk taking, market analysis, product development, business strategy, networking, financial management, startup, business creation",
    "Sales Manager": "Sales management, team leadership, customer relations, sales strategy, revenue generation, market development, client acquisition, business development, sales training",
    "HR Manager": "Human resources, talent management, recruitment, employee relations, performance management, training, organizational development, leadership, compliance, workforce planning",
    "Operations Manager": "Operations management, process optimization, supply chain, quality control, team management, efficiency improvement, strategic planning, leadership, business operations",
    "Supply Chain Manager": "Supply chain management, logistics, procurement, inventory management, vendor relations, operations, cost optimization, strategic planning, distribution, warehousing",
    "Accountant": "Accounting, financial reporting, tax preparation, auditing, financial analysis, bookkeeping, compliance, financial management, business finance, tax planning",
    "Auditor": "Auditing, financial analysis, compliance, risk assessment, internal controls, financial reporting, investigation, accounting, business analysis, financial review",
    "Real Estate Agent": "Real estate, property sales, client relations, market analysis, property management, sales, customer service, property investment, real estate transactions",
    "Insurance Agent": "Insurance sales, risk assessment, client relations, financial planning, customer service, insurance products, policy management, sales, financial services",
    "Bank Manager": "Banking, financial services, customer service, team management, financial planning, loan processing, banking operations, leadership, financial management",
    "Tax Consultant": "Tax planning, tax preparation, financial consulting, tax law, accounting, financial analysis, tax compliance, financial planning, tax strategy, business consulting",
    
    # Creative & Arts Careers
    "Graphic Designer": "Visual design, creativity, Adobe Creative Suite, branding, typography, layout design, digital art, marketing materials, artistic skills, logo design, print design",
    "Artist": "Creative arts, painting, drawing, sculpture, artistic expression, creativity, visual arts, art history, artistic techniques, portfolio development, fine arts",
    "Writer": "Creative writing, content creation, storytelling, editing, research, communication, journalism, publishing, literary skills, written communication, copywriting",
    "Photographer": "Photography, visual storytelling, camera skills, photo editing, creative vision, artistic expression, digital media, visual communication, portfolio, wedding photography",
    "Video Editor": "Video production, video editing, post-production, creative storytelling, visual effects, motion graphics, digital media, film production, technical skills, video content",
    "Music Producer": "Music production, audio engineering, sound design, music composition, recording, mixing, mastering, creative music, technical audio skills, music industry",
    "Interior Designer": "Interior design, space planning, creativity, design aesthetics, color theory, furniture selection, architectural knowledge, client relations, design software, home design",
    "Fashion Designer": "Fashion design, creativity, textile knowledge, trend analysis, sketching, pattern making, fashion industry, artistic skills, brand development, clothing design",
    "Animator": "Animation, 3D modeling, visual effects, creative storytelling, digital art, character design, motion graphics, technical skills, artistic expression, film animation",
    "Content Creator": "Content creation, social media, digital marketing, creative writing, video production, storytelling, brand building, audience engagement, creativity, digital content",
    "Social Media Manager": "Social media marketing, content strategy, digital marketing, community management, analytics, brand management, online engagement, marketing, social media strategy",
    "Advertising Executive": "Advertising, marketing strategy, creative campaigns, brand management, client relations, market research, creative thinking, business development, ad campaigns",
    "Film Director": "Film production, creative direction, storytelling, visual arts, leadership, film industry, creative vision, movie making, entertainment industry, artistic direction",
    "Architect": "Architecture, design, construction, building design, creative design, technical skills, project management, urban planning, structural design, architectural planning",
    "Web Designer": "Web design, user interface design, creativity, HTML, CSS, visual design, user experience, website development, digital design, responsive design",
    "Game Designer": "Game design, creativity, game development, storytelling, user experience, game mechanics, creative design, entertainment industry, interactive design, game industry",
    
    # Education & Training Careers
    "Teacher": "Education, teaching, curriculum development, student development, classroom management, educational psychology, subject expertise, communication, leadership, student mentoring",
    "Professor": "Higher education, research, academic teaching, scholarly work, curriculum development, student mentoring, academic writing, subject expertise, leadership, university teaching",
    "Educational Administrator": "Education management, school administration, policy development, staff management, budget management, educational leadership, strategic planning, school management",
    "Curriculum Developer": "Curriculum design, educational content, instructional design, learning objectives, educational technology, assessment design, educational research, learning design",
    "Librarian": "Information management, research assistance, cataloging, digital resources, information literacy, community service, knowledge organization, education, library science",
    "Training Specialist": "Training development, instructional design, employee development, learning management, presentation skills, curriculum design, adult education, corporate training",
    "Academic Researcher": "Research, data analysis, academic writing, scholarly work, critical thinking, methodology, publication, knowledge creation, analytical skills, scientific research",
    "School Counselor": "Student counseling, mental health support, career guidance, educational psychology, student development, crisis intervention, communication, empathy, student support",
    "Tutor": "Teaching, education, student support, academic assistance, subject expertise, communication, student mentoring, educational support, personalized learning, academic tutoring",
    "Educational Technology Specialist": "Educational technology, digital learning, technology integration, online education, learning management systems, educational software, digital education",
    "Language Instructor": "Language teaching, education, communication, cultural exchange, language learning, teaching methodology, student development, language education, foreign languages",
    "Special Education Teacher": "Special education, teaching, student support, educational psychology, inclusive education, student development, specialized teaching, educational support",
    
    # Engineering & Technical Careers
    "Mechanical Engineer": "Mechanical systems, engineering design, manufacturing, thermodynamics, materials science, CAD, problem solving, technical analysis, innovation, product development",
    "Civil Engineer": "Infrastructure design, construction, structural engineering, project management, environmental engineering, surveying, technical analysis, public works, building design",
    "Electrical Engineer": "Electrical systems, power systems, electronics, circuit design, automation, renewable energy, technical analysis, problem solving, innovation, electrical design",
    "Chemical Engineer": "Chemical processes, manufacturing, process design, materials science, safety engineering, environmental engineering, technical analysis, innovation, chemical processes",
    "Aerospace Engineer": "Aircraft design, space technology, aerodynamics, propulsion systems, materials science, technical analysis, innovation, research, engineering, aviation technology",
    "Environmental Engineer": "Environmental protection, sustainability, pollution control, water treatment, environmental impact assessment, technical analysis, public health, environmental science",
    "Industrial Engineer": "Process optimization, manufacturing, quality control, systems analysis, efficiency improvement, technical analysis, operations research, management, industrial systems",
    "Petroleum Engineer": "Oil and gas industry, energy sector, drilling, reservoir engineering, technical analysis, energy production, petroleum technology, engineering, energy engineering",
    "Nuclear Engineer": "Nuclear technology, energy production, nuclear power, technical analysis, safety engineering, nuclear physics, energy engineering, technical skills, nuclear technology",
    "Marine Engineer": "Marine technology, ship design, ocean engineering, technical analysis, maritime industry, marine systems, engineering, technical skills, marine technology",
    "Mining Engineer": "Mining industry, mineral extraction, technical analysis, safety engineering, resource management, engineering, technical skills, mining technology, geological engineering",
    "Telecommunications Engineer": "Telecommunications, network design, communication systems, technical analysis, wireless technology, engineering, technical skills, communication technology",
    "Automotive Engineer": "Automotive industry, vehicle design, mechanical engineering, technical analysis, automotive technology, engineering, technical skills, vehicle development",
    
    # Science & Research Careers
    "Research Scientist": "Scientific research, laboratory work, data analysis, research methodology, scientific investigation, analytical skills, research and development, scientific knowledge",
    "Biologist": "Biology, life sciences, research, laboratory work, scientific investigation, environmental science, medical research, scientific knowledge, research and development",
    "Chemist": "Chemistry, laboratory work, chemical analysis, research, scientific investigation, analytical skills, chemical processes, scientific knowledge, research and development",
    "Physicist": "Physics, scientific research, mathematical analysis, research methodology, scientific investigation, analytical skills, theoretical physics, scientific knowledge, research",
    "Geologist": "Geology, earth sciences, field work, research, environmental analysis, scientific investigation, natural resources, scientific knowledge, geological research",
    "Environmental Scientist": "Environmental science, sustainability, research, environmental analysis, scientific investigation, environmental protection, scientific knowledge, environmental research",
    "Data Analyst": "Data analysis, statistical analysis, research, data interpretation, analytical skills, data visualization, research methodology, statistical knowledge, data science",
    "Laboratory Technician": "Laboratory work, scientific testing, research support, technical skills, laboratory analysis, scientific investigation, research assistance, technical knowledge",
    "Quality Control Analyst": "Quality control, testing, analysis, manufacturing, technical skills, quality assurance, analytical skills, product testing, quality management",
    "Forensic Scientist": "Forensic science, criminal investigation, laboratory work, scientific analysis, law enforcement, analytical skills, scientific investigation, forensic analysis",
    "Meteorologist": "Weather forecasting, atmospheric science, research, data analysis, scientific investigation, climate science, environmental science, scientific knowledge, weather analysis",
    "Astronomer": "Astronomy, space science, research, scientific investigation, observational analysis, astrophysics, scientific knowledge, space research, astronomical research",
    
    # Social Services & Community Careers
    "Social Worker": "Social services, community support, helping people, counseling, social justice, community development, social welfare, human services, community outreach",
    "Counselor": "Counseling, mental health, helping people, therapy, support services, human services, psychological support, guidance, emotional support, therapeutic services",
    "Community Health Worker": "Community health, public health, healthcare, community outreach, health education, helping people, community development, health promotion, public service",
    "Probation Officer": "Criminal justice, social services, helping people, rehabilitation, community supervision, law enforcement, social work, community safety, rehabilitation services",
    "Child Welfare Worker": "Child protection, social services, helping children, family services, child development, social work, community support, child advocacy, family support",
    "Substance Abuse Counselor": "Addiction counseling, mental health, helping people, therapy, rehabilitation, substance abuse treatment, counseling services, recovery support, therapeutic services",
    "Marriage and Family Therapist": "Family therapy, counseling, mental health, helping families, relationship counseling, therapeutic services, family support, mental health services, counseling",
    "Youth Counselor": "Youth services, counseling, helping young people, youth development, mentoring, educational support, youth advocacy, community services, youth support",
    "Elderly Care Coordinator": "Elderly care, healthcare, helping elderly, community services, healthcare coordination, senior services, community support, healthcare management, elderly support",
    "Disability Services Coordinator": "Disability services, helping people, community support, accessibility services, disability advocacy, community services, support services, disability support",
    
    # Legal & Law Enforcement Careers
    "Lawyer": "Legal practice, law, legal advice, court representation, legal research, advocacy, legal analysis, justice, legal services, legal representation, law practice",
    "Judge": "Legal system, justice, court proceedings, legal decision making, law, legal analysis, judicial services, legal authority, court management, legal judgment",
    "Paralegal": "Legal support, legal research, law office assistance, legal documentation, legal services, legal analysis, law support, legal assistance, legal research support",
    "Police Officer": "Law enforcement, public safety, community protection, criminal investigation, public service, community safety, law enforcement services, public security, community policing",
    "Detective": "Criminal investigation, law enforcement, detective work, crime solving, investigation, law enforcement services, criminal analysis, investigative services, crime investigation",
    "FBI Agent": "Federal law enforcement, criminal investigation, national security, law enforcement services, federal investigation, security services, law enforcement, federal security",
    "Immigration Officer": "Immigration services, law enforcement, border security, immigration law, public service, immigration processing, border control, immigration enforcement, public security",
    "Court Reporter": "Legal services, court proceedings, legal documentation, transcription services, legal support, court services, legal documentation, court reporting, legal transcription",
    "Legal Assistant": "Legal support, law office assistance, legal research, legal documentation, legal services, legal assistance, law support, legal research support, legal office support",
    "Corrections Officer": "Corrections, law enforcement, prison management, public safety, correctional services, law enforcement services, prison security, correctional management, public security",
    
    # Agriculture & Food Careers
    "Agricultural Engineer": "Agriculture, farming, agricultural technology, crop production, agricultural systems, engineering, agricultural innovation, farming technology, agricultural development",
    "Food Scientist": "Food science, food safety, food production, research, food technology, food analysis, food quality, food research, food innovation, food development",
    "Farm Manager": "Farm management, agriculture, crop production, livestock management, agricultural operations, farming, agricultural business, farm operations, agricultural management",
    "Agricultural Inspector": "Agriculture, food safety, quality control, agricultural inspection, food inspection, agricultural compliance, food safety inspection, agricultural quality, food quality",
    "Horticulturist": "Plant science, gardening, plant cultivation, agricultural science, plant care, botanical science, plant research, agricultural research, plant development, botanical research",
    "Livestock Manager": "Livestock management, animal care, agriculture, farm management, animal husbandry, livestock production, agricultural management, animal management, farm operations",
    "Agricultural Consultant": "Agriculture, farming, agricultural consulting, crop production, agricultural advice, farming consultation, agricultural business, agricultural development, farming advice",
    "Food Safety Inspector": "Food safety, food inspection, quality control, food quality, food safety inspection, food compliance, food safety management, food quality control, food inspection",
    "Agricultural Researcher": "Agricultural research, crop research, agricultural science, research, agricultural development, farming research, agricultural innovation, agricultural studies, crop development",
    
    # Transportation & Logistics Careers
    "Pilot": "Aviation, flying, aircraft operation, transportation, aviation safety, flight operations, aviation technology, air transportation, aviation services, flight management",
    "Air Traffic Controller": "Aviation, air traffic control, aviation safety, flight operations, aviation technology, air transportation, aviation services, flight management, aviation control",
    "Truck Driver": "Transportation, logistics, delivery services, transportation services, logistics management, transportation operations, delivery operations, transportation logistics, freight transport",
    "Logistics Coordinator": "Logistics, supply chain, transportation, logistics management, supply chain management, logistics operations, transportation logistics, logistics planning, supply chain operations",
    "Shipping Manager": "Shipping, logistics, transportation, supply chain, logistics management, shipping operations, transportation logistics, logistics planning, supply chain operations",
    "Railroad Engineer": "Railroad, transportation, railway operations, transportation engineering, railway technology, transportation services, railway management, transportation operations, railway services",
    "Marine Captain": "Maritime, shipping, marine transportation, maritime operations, marine services, maritime management, marine operations, maritime services, marine transportation",
    "Flight Attendant": "Aviation, customer service, flight operations, aviation services, customer care, aviation safety, flight services, aviation hospitality, flight management, aviation services",
    "Transportation Planner": "Transportation planning, urban planning, transportation systems, transportation analysis, transportation development, transportation management, transportation services, transportation operations",
    "Warehouse Manager": "Warehouse management, logistics, supply chain, inventory management, logistics operations, supply chain management, warehouse operations, logistics planning, supply chain operations",
    
    # Sports & Fitness Careers
    "Personal Trainer": "Fitness, health, exercise, personal training, fitness coaching, health coaching, exercise training, fitness instruction, health and fitness, fitness guidance",
    "Sports Coach": "Sports, coaching, athletic training, sports instruction, team management, sports development, athletic coaching, sports training, team coaching, sports leadership",
    "Sports Medicine Physician": "Sports medicine, healthcare, medical care, athletic medicine, sports healthcare, medical treatment, sports injury treatment, healthcare services, medical care",
    "Athletic Trainer": "Athletic training, sports medicine, injury prevention, sports healthcare, athletic care, sports training, injury treatment, sports health, athletic healthcare, sports care",
    "Fitness Instructor": "Fitness instruction, exercise training, health and fitness, fitness coaching, exercise instruction, fitness training, health coaching, fitness guidance, exercise coaching",
    "Sports Psychologist": "Sports psychology, mental health, athletic performance, psychological support, sports counseling, mental training, sports therapy, psychological services, sports mental health",
    "Recreation Therapist": "Recreation therapy, therapeutic recreation, healthcare, patient care, recreational activities, therapeutic services, healthcare services, recreational therapy, therapeutic activities",
    "Sports Nutritionist": "Sports nutrition, nutrition counseling, health, dietary planning, sports health, nutrition planning, health education, sports wellness, nutrition guidance, sports nutrition planning",
    "Gym Manager": "Gym management, fitness management, health and fitness, fitness operations, health club management, fitness business, health and fitness management, fitness operations management",
    
    # Media & Communication Careers
    "Journalist": "Journalism, news reporting, writing, communication, media, news writing, investigative reporting, media communication, news media, communication services, media reporting",
    "News Anchor": "News broadcasting, media, communication, television, broadcasting, news presentation, media communication, broadcast journalism, news media, communication services",
    "Radio Host": "Radio broadcasting, media, communication, broadcasting, radio programming, media communication, broadcast services, radio media, communication services, radio entertainment",
    "Public Relations Specialist": "Public relations, communication, media relations, brand management, communication strategy, public communication, media communication, communication services, public communication",
    "Marketing Communications Manager": "Marketing communication, communication, marketing, brand communication, communication strategy, marketing strategy, communication services, marketing communication, brand communication",
    "Event Planner": "Event planning, event management, event coordination, event services, event organization, event management services, event coordination services, event planning services, event services",
    "Media Producer": "Media production, content production, media creation, production management, media services, content creation, media production services, production services, media creation services",
    "Broadcast Technician": "Broadcasting, media technology, technical services, broadcast technology, media technical services, broadcast technical services, media technical support, broadcast technical support",
    "Film Producer": "Film production, movie production, entertainment production, film industry, entertainment industry, production management, film services, entertainment services, production services",
    "Podcast Host": "Podcasting, media, communication, audio content, media communication, podcast production, audio media, communication services, podcast services, audio communication",
    
    # Hospitality & Tourism Careers
    "Hotel Manager": "Hotel management, hospitality, customer service, hospitality management, hotel operations, hospitality services, customer care, hospitality business, hotel services, hospitality operations",
    "Chef": "Cooking, culinary arts, food preparation, culinary skills, restaurant, food service, culinary creativity, food creation, culinary arts, food preparation, culinary services",
    "Travel Agent": "Travel planning, tourism, travel services, travel coordination, travel management, tourism services, travel assistance, travel planning services, tourism planning, travel services",
    "Event Coordinator": "Event coordination, event planning, event management, event services, event organization, event coordination services, event planning services, event services, event management services",
    "Restaurant Manager": "Restaurant management, food service, hospitality, customer service, restaurant operations, hospitality management, food service management, restaurant services, hospitality services",
    "Tour Guide": "Tourism, travel, customer service, travel services, tourism services, travel guidance, tourism guidance, travel assistance, tourism assistance, travel services",
    "Concierge": "Customer service, hospitality, guest services, hospitality services, customer care, hospitality care, guest assistance, hospitality assistance, customer assistance, hospitality support",
    "Catering Manager": "Catering, food service, event catering, food service management, catering services, food service services, catering management, food service operations, catering operations",
    "Spa Manager": "Spa management, wellness, health services, wellness services, spa services, wellness management, health and wellness, spa operations, wellness operations, health services",
    "Cruise Director": "Cruise management, hospitality, entertainment, customer service, hospitality services, entertainment services, customer care, hospitality care, entertainment management, hospitality management"
}